#!/bin/bash

source projects.sh

for param in "$@"
do
    if [ -z "$(cat cookie)" ]; then
        echo "cookie autenticantion missing"
    else 
        case $param in
            projeto)
                project "$2"
                ;;
        esac
    fi
done

